import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner";
import { useCallback } from "react";

const Home = () => {
  const handleClick = useCallback(() => {
    alert("hi");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Store Locator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText={"View stores nearby"} handleClick={handleClick} />
      </main>
    </div>
  );
};
export default Home;
